version: "3.8"

services:
  medlr:
    build: .
    ports:
      - "8008:8008"
    restart: always

    environment:
#      PROMETHEUS_HOST: prometheus
      MONGO_URI: mongodb://root:thisissomethingsecret@mongo:27017/
      APP_URL: medlr:8008
#    depends_on:
#      - prometheus
#    networks:
#      - monitoring

#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - monitoring

#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    depends_on:
#      - prometheus
#    networks:
#      - monitoring
#    environment:
#      GF_SECURITY_ADMIN_PASSWORD: admin
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./docker_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: thisissomethingsecret

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: thisissomethingsecret
      ME_CONFIG_MONGODB_URL: mongodb://root:thisissomethingsecret@mongo:27017/
volumes:
  mongodb_data:

#networks:
#  monitoring:
#    driver: bridge
